[book]
authors = ["Jáchym Tomášek"]
language = "en"
multilingual = false
src = "src"
title = "Kelp Book"

[preprocessor.links]

[output.html]
site-url = "docs/kelp/"
git-repository-url = "https://github.com/kelp-lang/docs-kelp"
git-repository-icon = "fa-github"